name: CI
on:
  push:
  schedule:
    - cron: 13 21 * * *

jobs:
  docker-build-cache:
    name: docker build cache
    runs-on: [linux, large, docker]
    steps:
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - uses: docker/build-push-action@v5
        id: build
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/server
          target: builder
          load: true

  cljfmt-check:
    name: cljfmt check
    runs-on: [ linux, large ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 'latest'
          cljfmt: 'latest'
      - run: make cljfmt-check

  clj-kondo-lint:
    name: clj-kondo lint
    runs-on: [ linux, large ]
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 'latest'
          clj-kondo: 'latest'
      - run: make clj-kondo-lint-ci

  test:
    name: run tests
    needs: docker-build-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/server
          target: builder
          load: true
      - name: Run tests
        run: docker run fluree/server make test

  notifications:
    name: send notifications
    if: always()
    runs-on: [linux, large, docker]
    needs: [test]
    steps:
      - name:
        if: github.ref == 'refs/heads/main' && failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel: development
          status: FAILED
          color: danger
